import { Container } from '@/components/shared/container'
import { Metadata } from 'next'
import { Sidebar, SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'

export const metadata: Metadata = {
    title: 'Profile',
    description: 'Generated by create next app',
}

export default function ProfileLayout({ children }: { children: React.ReactNode }) {
    return (
        <SidebarProvider>
            <Sidebar />
            <main className="">
                <SidebarTrigger />
                <Container>{children}</Container>
            </main>
        </SidebarProvider>
    )
}
