import { Container } from '@/components/shared/container'
import { Metadata } from 'next'
import { Header } from '@/components/shared/header'

export const metadata: Metadata = {
    title: 'Profile',
    description: 'Generated by create next app',
}

export default function ProfileLayout({ children }: { children: React.ReactNode }) {
    return (
        <>
            <Header />
            <main className="w-full">
                <Container>{children}</Container>
            </main>
        </>
    )
}
