import { Container } from '@/widgets/container/container'
import { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Profile',
    description: 'Generated by create next app',
}

export default function ProfileLayout({ children }: { children: React.ReactNode }) {
    return (
        <>
            <main className="w-full">
                <Container>{children}</Container>
            </main>
        </>
    )
}
